site_learn_it/apiapp/urls.py
from django.urls import path, include
from .views import UserViewSet, CourseViewSet, GroupList, LoginView


urlpatterns = [
    path("o/", include('oauth2_provider.urls', namespace='oauth2_provider')),
    # path("token/", include('oauth2_provider.urls', namespace='token')),
    path("users/", UserViewSet.as_view({'get': 'list', 'post': 'create'}), name='apiusers'),
    path("users/<pk>", UserViewSet.as_view({'get': 'retrieve'}), name='user-detail'),
    path("groups/", GroupList.as_view()),
    path("courses/", CourseViewSet.as_view({'get': 'list', 'post': 'create'}), name='apicourses'),
    path("courses/<pk>", CourseViewSet.as_view({'get': 'retrieve'})),
    path("login/", LoginView.as_view(), name="login"),
    ]

site_learn_it/learn_it/urls.py
from django.urls import path
from . import views

app_name = 'learn_it'

urlpatterns = [
    path('', views.index, name='index'),
    path('courses', views.CourseListView.as_view(), name='course-list'),
    path('course/<pk>', views.course_detail, name='course'),
    path('courses/create/', views.CourseCreateView.as_view(), name='course-create'),
    path('courses/update/<pk>', views.CourseUpdateView.as_view(), name='course-update'),
    path('courses/delete/<pk>', views.CourseDeleteView.as_view(), name='course-delete'),
    path('register/', views.register, name='register'),
    path('accounts/login/', views.login_view, name='login-user'),
    path('contacts', views.ContactsView.as_view(), name='contacts'),
    path('statistics', views.StatisticsView.as_view(), name='statistics'),
]

site_learn_it/site_learn_it/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from . import settings
from django.conf.urls.static import static

from rest_framework import routers
from apiapp import views

from graphene_django.views import GraphQLView
from .schema import schema


router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'courses', views.CourseViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('learn_it/', include('learn_it.urls')),
    path('', RedirectView.as_view(url='/learn_it/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api-oauth/', include('apiapp.urls')),
    path('graphql/', GraphQLView.as_view(graphiql=True, schema=schema)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns 

urlpatterns += [
    path('django-rq/', include('django_rq.urls'))
]

site_learn_it/learn_it/models.py
from django.db import models
from site_learn_it import settings
from django.contrib.auth.models import AbstractUser, UserManager


class CustomUser(AbstractUser):
    """Обучающийся и преподаватель"""

    USER_TYPE_CHOICE = (
        ('s', 'Student'),
        ('t', 'Teacher')
    )
    role = models.CharField('роль', max_length=1, choices=USER_TYPE_CHOICE, default='s', help_text='Выберите свою роль')

    objects = UserManager()

    @property
    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f"{self.get_full_name}"

    def get_all_courses(self):
        courses_qs = Course.objects.filter(students=self.id)
        return [x.title for x in courses_qs]


class Days(models.Model):

    DAYS = (
        (1, "Понедельник"),
        (2, "Вторник"),
        (3, "Среда"),
        (4, "Четверг"),
        (5, "Пятница"),
        (6, "Суббота"),
        (7, "Воскресенье")
    )

    day = models.CharField('день недели', max_length=256, null=True, blank=True)

    def __str__(self):
        return f'{self.id} {self.day}'


class Course(models.Model):
    """Курс: python, java, экономика математика и т.д."""

    title = models.CharField('название', max_length=200)
    duration = models.CharField('продолжительность', max_length=50)
    about = models.TextField('о курсе', max_length=1000, null=True, blank=True)
    course_pic = models.ImageField( null=True, blank=True)
    students = models.ManyToManyField(CustomUser, related_name='courses', blank=True)
    date_start = models.DateField(auto_now_add=True, editable=True)
    
    day = models.ManyToManyField(Days, related_name='days')

    def __str__(self):
        return f"{self.title}"

    def get_short_description(self):
        return self.about [:70]


    # TODO Добавить функцию date_finish (date_start + duration)
    # TODO Добавить функцию is_active (date_finish - today)

site_learn_it/learn_it/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'role',
        )


class EditProfileForm(UserChangeForm):
    template_name = '/user/edit/'

    class Meta:
        model = CustomUser
        fields = (
            'first_name',
            'last_name',
            'email',
            'password'
            )


class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', widget=forms.TextInput)
    email = forms.EmailField(widget=forms.EmailInput)
    message = forms.CharField(label='сообщение', widget=forms.Textarea)

site_learn_it/learn_it/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from .models import Course, CustomUser, Days
from django.utils import timezone
from .forms import RegistrationForm, LoginForm, ContactForm
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.template.context_processors import csrf
from .tasks import send_mail_from_form

from datetime import timedelta
from django.utils import timezone

from django.db.models import Q, F, Max, Min, Exists, OuterRef, Sum, Count, Subquery


def index(request):
    return render(request, 'learn_it/index.html')


class CourseListView(ListView):

    model = Course
    paginate_by = 50  # if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['now'] = timezone.now()
        return context



def course_detail(request, pk):
    """детали курса"""
    course_data = Course.objects.get(id=pk)
    days = Days.objects.filter(days__id=pk)
    context = {'course': course_data, 'days': days}

    if request.method == 'GET':
        return render(request, 'learn_it/course_detail.html', context)

    if request.method == 'POST':
        
        if request.POST.get('subscribe') == 'del':
            course_data.students.remove(request.user)
        else:
            course_data.students.add(request.user)

        return render(request, 'learn_it/course_detail.html', context)


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/login/')
        return render(request, 'registration/register.html', {'form': form})
    else:
        form = RegistrationForm()
        
        return render(request, 'registration/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect('learn_it:course-list')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    template_name = 'learn_it/course_create_form.html'
    success_url = reverse_lazy('learn_it:course-list')
    fields = ['title', 'duration', 'about', 'course_pic', 'day',]


class CourseUpdateView(LoginRequiredMixin, UpdateView):
    model = Course
    template_name = 'learn_it/course_create_form.html'
    success_url = reverse_lazy('learn_it:course-list')
    fields = ['title', 'duration', 'about', 'course_pic', 'day',]


class CourseDeleteView(DeleteView):
    model = Course
    success_url = reverse_lazy('learn_it:course-list')

    @method_decorator(user_passes_test(lambda u: u.is_superuser,
                     login_url=reverse_lazy('learn_it:login-user')))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ContactsView(View):
    template_name = 'learn_it/contacts.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context.update(csrf(request))
        context['contact_form'] = ContactForm()

        return render(request, template_name=self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        context = {}
        form = ContactForm(request.POST)


        if form.is_valid():

            email_body = f"{form.cleaned_data['message']}"
            email_to_answer = f"{form.cleaned_data['email']}"

            # call celery task
            send_mail_from_form.delay(email_to_answer, email_body)

        return render(request, template_name=self.template_name, context=context)


class StatisticsView(View):
    template_name = 'learn_it/statistics.html'

    def get(self, request, *args, **kwargs):
        context = {}

        one_month_ago = timezone.now() - timedelta(days=30)

        popular_courses_in_month = Course.objects.filter(
            Exists(CustomUser.objects.filter(courses=OuterRef('pk'), date_joined__gte=one_month_ago)))
        context['popular_courses_in_month'] = popular_courses_in_month

        popular_courses = Course.objects.values('title').annotate(count=Count('students')).order_by('-count')[:10]

        context['popular_courses'] = popular_courses
        context['most_popular'] = popular_courses.first()

        longest_duration = Course.objects.all().aggregate(Max('duration'))
        longest_course = Course.objects.get(duration=longest_duration['duration__max'])
        context['longest_course'] = longest_course

        busiest_days = Course.objects.values('day').annotate(count=Count('day')).order_by('-count')
        context['busiest_days'] = busiest_days

        return render(request, template_name=self.template_name, context=context)

site_learn_it/learn_it/templates/learn_it/contacts.html
{% extends 'base.html' %}
{% block title %}Контакты{% endblock %}
{% load static %}
{% block header %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'learn_it:index' %}">Главная</a></li>
      <li class="breadcrumb-item active" aria-current="page">Контакты</li>
    </ol>
  </nav>
    <h2>Связаться с нами:</h2>
{% endblock header %}
{% block content %}
    <article>
    {% if contact_form %}

        <p>Если у Вас есть пожелания или предложения, то вы можете отправить нам их, воспользовавшись контактной формой:</p>
        <form id="contact_form" action="{% url 'learn_it:contacts' %}" method="post">
            {% csrf_token %}
            {{ contact_form.as_p }}
            <p>{{ form.name.errors.as_text }}</p>
            <p>{{ form.email.errors.as_text }}</p>
            <p>{{ form.message.errors.as_text }}</p>
                <button type="submit" class="btn btn-primary">Отправить</button>

        </form>
    {% else %}
        <p>Сообщение отправлено</p>
    {% endif %}
    </article>
{% endblock %}

site_learn_it/learn_it/templates/learn_it/course_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'learn_it:index' %}">Главная</a></li>
      <li class="breadcrumb-item"><a href="{% url 'learn_it:course-list' %}">Курсы</a></li>
      <li class="breadcrumb-item active" aria-current="page">Создать курс</li>
    </ol>
  </nav>
{% endblock header %}

{% block content %}

    <div class course-delete-form>
        {% if user.is_authenticated %}
           
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}     
                    <input type="submit" class="btn btn-light" value="Удалить" />
                </form>
                <button>
                    <a href="{% url 'learn_it:course' course.pk %}">Отменить</a>
                </button>
        {% endif %}
    </div>
    
{% endblock content %}

site_learn_it/learn_it/templates/learn_it/course_create_form.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'learn_it:index' %}">Главная</a></li>
      <li class="breadcrumb-item"><a href="{% url 'learn_it:course-list' %}">Курсы</a></li>
      <li class="breadcrumb-item active" aria-current="page">Создать курс</li>
    </ol>
  </nav>
{% endblock header %}

{% block content %}

    <div class course-record-form>
        {% if user.is_authenticated %}
           
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}     
                    <input type="submit" class="btn btn-light" value="Сохранить" />
                </form>
        {% endif %}
    </div>
    
{% endblock content %}

site_learn_it/learn_it/templates/learn_it/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'learn_it:index' %}">Главная</a></li>
      <li class="breadcrumb-item"><a href="{% url 'learn_it:course-list' %}">Курсы</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ course.title }}</li>
    </ol>
  </nav>
    <h2>{{ course.title }}</h2>
{% endblock header %}

{% block content %}
    <div class="row">
        
        <p>{{ course.about }}
        </p>
    </div>
    <hr>
    <div class course-detail>
        <p> Продолжительность курса: {{ course.duration }} мес.</p>
        {% if user.is_authenticated%}
            {% if course.title not in user.get_all_courses %}
                <form method="post" action="">
                    {% csrf_token %}       
                    <input type="submit" class="btn btn-light" value="Поступить на курс" />
                    <input type="hidden" name="pk" value="{{ course.id }}" />
                </form>
            {% else %}
                <form method="post" action="">
                    {% csrf_token %}       
                    <input type="submit" class="btn btn-light" value="Отписаться" />
                    <input type="hidden" name="pk" value="{{ course.id }}" />
                    <input type="hidden" name="subscribe" value="del" />
                </form>
                <p>Дни проведения занятий:
                    <ul class="days">
                        {% for day in days %}
                        <li class="nav-item active">{{day.day}}</li>
                        {%endfor%}
                    </ul>
                    <br>
                    Время проведения: 20:00 Мск
                </p>
            {% endif %}
        {% else %}
        <p>Поступить на курс могут только зарегистрированные пользователи</p>
        {% endif %}
    </div>
    <div class="links">
        {% if user.is_authenticated %}
        <div class="link">
            <a href="{% url 'learn_it:course-update' course.pk %}">Редактировать курс</a>
            <a href="{% url 'learn_it:course-delete' course.pk %}">Удалить курс</a>
        </div>
        {% endif %}

    </div>
    
{% endblock content %}

site_learn_it/learn_it/templates/learn_it/course_list.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'learn_it:index' %}">Главная</a></li>
      <li class="breadcrumb-item active" aria-current="page">Курсы</li>
    </ol>
  </nav>
    <h2>Доступные курсы:</h2>
{% endblock header %}

{% block content %}
    {% for course in course_list%}
    <div class="row">
        <div class="jumbotron col-lg-12">
            <div class="col-md-3 col-lg-3">
                <a href="{% url 'learn_it:course' course.id %}"><h1>{{ course }}</h1></a>
            </div>
            <div class="col-md-3 col-lg-3">
                {% if course.course_pic.url is not None%}
                    <img src="{{ course.course_pic.url }}" width="100" alt="{{course}}"/>
                {% else %}
                    <img src="" width="100" alt="{{course}}"/>
                {% endif %}
            </div>
            <div class="course-descr col-md-12 col-lg-12 ">
                {{ course.about }}
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock content %}

site_learn_it/learn_it/templates/learn_it/index.html
{% extends 'base.html' %}

{% block header %}
    <div class="jumbotron">
        <h1>Track your courses</h1>
    </div>
{% endblock header %}

{% block content %}
    {% if not user.is_authenticated %}
    <h2>
        <a href="{% url 'learn_it:register' %}">Register an account</a>
        to pass the course to improove your knowledge.
    </h2>
    {% endif %}
    <h2>
        Whenever you learn something new about a course, don't give up.
    </h2>

{% endblock content %}

site_learn_it/learn_it/templates/learn_it/statistics.html
{% extends 'base.html' %}
{% block title %}Статистика{% endblock %}
{% load static %}
{% block header %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'learn_it:index' %}">Главная</a></li>
        <li class="breadcrumb-item active" aria-current="page">Статистика</li>
    </ol>
</nav>
<h2>Статистика по сайту:</h2>
{% endblock header %}
{% block content %}

<p> Пользователи, зарегистрированные в этом месяце подписались на следующие курсы:</p>
<ul>
    {% for course in popular_courses_in_month %}
    <li>{{ course }}</li>
    {% endfor %}
</ul>

<p>Самые популярные курсы на сайте:</p>
<ul>
    {% for course in popular_courses %}
    <li>{{ course.title }} : {{ course.count }} человек</li>
    {% endfor %}
</ul>

<p>Лидер среди них: {{ most_popular.title }}</p>
<p>Самый длинный курс: {{ longest_course.title }} длительностью {{ longest_course.duration }} месяцев</p>
<p>Самые нагруженные дни: </p>
<ul>
    {% for day in busiest_days %}
    <li>{{ day.day }} </li>
    {% endfor %}
</ul>
{% endblock %}